version: '3'

services:
  house-price-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 